homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index_page, name='index'),
    path('articles/', views.articles, name='articles'),
]

myproj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('homepage/', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render
from django.views.decorators.http import require_http_methods, require_GET


@require_http_methods(['GET', 'POST'])
def index_page(request):
    return render(request, 'homepage/index.html')


@require_GET
def articles(request):
    args = {
        'articles': list(range(1, 8)),
        'val1': '<h3>Value1</h3>',
        'val2': '<h4>Value2</h4>'
    }
    return render(request, 'homepage/articles.html', args)

homepage/templates/homepage/articles.html
{% extends 'homepage/base.html' %}

{% block title%}
Articles page
{% endblock %}

{% block body %}
<h1>Choose an article!</h1>
<ul class="list-group">
  {% for num in articles %}
  {% cycle val1 val2 as val silent %}
  <li class="list-group-item {% cycle 'list-group-item-primary' 'list-group-item-success' 'list-group-item-warning' %}">Article №{{ num }} {{ val|safe }}</li>
  {% endfor %}
  {% cycle 'dark' 'danger' as theme silent %}

  <li class="list-group-item list-group-item-{{ theme }} ">A simple primary list group item</li>
  <li class="list-group-item list-group-item-{{ theme }}">A simple secondary list group item</li>
  
</ul>
{% endblock %}

homepage/templates/homepage/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <title>
  {% block title%}
  Base
  {% endblock %}
  </title>
</head>
<body>
  <br>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled">Later</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <br>

      {% block body %}
      <h1>Override me!</h1>
      {% endblock %}
      <hr>
      <a href="{% url 'homepage:index' %}">Visit index</a>
      <a href="{% url 'homepage:articles' %}">Visit articles</a>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

homepage/templates/homepage/index.html
{% extends 'homepage/base.html' %}

{% block title%}
  Index page
{% endblock %}

{% block body %}
<h1>Welcome to index page!</h1>
{% endblock %}